### ISSUE TITLE
您好，该机型有办法解决外接显示器的问题吗？

### ISSUE THREAD

**Issue by whxcode** [Rocky7842/Msi-Gs66-Opencore-Hackintosh#1]

**Comment by Rocky7842** [comment]
沒辦法，因為外接顯示器接口都是屬於獨顯直連。

**Comment by whxcode** [comment]
> 沒辦法，因為外接顯示器接口都是屬於獨顯直連。



> 沒辦法，因為外接顯示器接口都是屬於獨顯直連。

谢谢。

**Comment by whxcode** [comment]
> 沒辦法，因為外接顯示器接口都是屬於獨顯直連。

或者，有没有其它道处理方案呢？

**Comment by Rocky7842** [comment]
> > 沒辦法，因為外接顯示器接口都是屬於獨顯直連。
> 
> 或者，有没有其它道处理方案呢？

可以使用thunderbolt外接顯示卡。
或是我有看過一些macos下usb轉hdmi的轉換器(實際上就是外接顯示晶片)，你可以上網查看看。不確定相容性以及性能如何，建議有查到的話可以詢問賣家。

**Comment by whxcode** [comment]
> > > 沒辦法，因為外接顯示器接口都是屬於獨顯直連。
> > 
> > 
> > 或者，有没有其它道处理方案呢？
> 
> 可以使用thunderbolt外接顯示卡。(附註：此EFI thunderbolt理論上可用，但因為我沒有thunderbolt裝置因此沒有進行測試。) 或是我有看過一些macos下usb轉hdmi的轉換器(實際上就是外接顯示晶片)，你可以上網查看看。不確定相容性以及性能如何，建議有查到的話可以詢問賣家。

谢谢
