### ISSUE TITLE
请问你这个高刷是怎么开启的呢

### ISSUE THREAD

**Issue by look4uz** [Rocky7842/Msi-Gs66-Opencore-Hackintosh#2]
请问你是怎么开启高刷的呢，我也是同样的机型 13的系统，设置里根本找不到开启高刷的地方，而且我注入了显示器的edid也没用，不能高刷只能60Hz，求救

**Comment by Rocky7842** [comment]
在MacOS Ventura 13.0.1沒有此問題發生，請確定版本正確且沒有自行更動EFI導致問題發生。

**Comment by look4uz** [comment]
我是说这个刷新率在哪里调呢？我找不到刷新率的选项
