### ISSUE TITLE
Black screen occurs in mac recovery

### ISSUE THREAD

**Issue by xmnily** [Rocky7842/Msi-Gs66-Opencore-Hackintosh#4]
One small problem was that the screen would die when I entered the macOS installation screen (Apple logo). My solution was to repeatedly tap the laptop keyboard which would occasionally light up the screen. What kind of question is that

**Comment by Rocky7842** [comment]
Tried boot to 13.3.1 recovery. No such issue on my device.

**Comment by xmnily** [comment]
非常感谢 我在最初搞错了版本 用的13.4 
后来改为13.3.1 再次进行尝试
真的就是完美两个字
作者大大非常厉害 辛苦了🙏
